name: STM32 UART Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  test-uart:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - uses: actions/checkout@v4
      
      - name: Run STM32 UART Test
        run: |
          echo "=== Running STM32 Bootloader Test ==="
          python3 ~/actions-runner/stm32_uart_test.py
