name: Unit Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:    # Add this line to enable manual triggers

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # Important for Unity framework
    
    - name: Build and run tests
      run: |
        docker build -t stm32-build .
        docker run --rm stm32-build make test