name: Unit Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # Important for Unity framework
    
    - name: Build and run tests
      run: |
        docker build -t stm32-build .
        # Debug: Check files in container
        docker run --rm stm32-build ls -la /workspaces
        docker run --rm stm32-build ls -la /workspaces/inc
        docker run --rm stm32-build ls -la /workspaces/src
        docker run --rm stm32-build ls -la /workspaces/tests
        # Run tests
        docker run --rm stm32-build make test